import './globals.css'
import {Inter} from 'next/font/google'
import {Navbar} from "@/components/Navbar";
import {NextAuthProvider} from "@/app/provider";
import Sidebar from "@/components/Sidebar";

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'Github OAuth Sign In Next App',
  // description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <NextAuthProvider>
        <div className="flex h-screen">
          {/* Sidebar */}
          <Sidebar />

          {/* Content */}
          <div className="flex flex-col flex-1 overflow-hidden">
            {/* Navbar */}
            <Navbar />

            {/* Main Content */}
            <div className="flex flex-col flex-1 overflow-y-auto px-8 py-4">
              {/* Page Content */}
              {children}
            </div>
          </div>
        </div>


        {/*<div className='max-w-5xl mx-auto px-8'>
          <Navbar/>
          <div className='pt-16'>
            {children}
          </div>
        </div>*/}
      </NextAuthProvider>
      </body>
      </html>
  )
}
